// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package worldbuilder

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WorldAttributeDefinition struct {
	ID            pgtype.UUID        `json:"id"`
	Wbatn         string             `json:"wbatn"`
	AttributeName string             `json:"attribute_name"`
	Label         string             `json:"label"`
	DataType      string             `json:"data_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WorldEntity struct {
	ID                pgtype.UUID        `json:"id"`
	TypeID            pgtype.UUID        `json:"type_id"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	Wbrn              string             `json:"wbrn"`
	EntityName        string             `json:"entity_name"`
	EntityDescription string             `json:"entity_description"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type WorldEntityAttribute struct {
	ID             pgtype.UUID        `json:"id"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	AttributeID    pgtype.UUID        `json:"attribute_id"`
	AttributeValue string             `json:"attribute_value"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorldType struct {
	ID              pgtype.UUID        `json:"id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Wbtn            string             `json:"wbtn"`
	TypeName        string             `json:"type_name"`
	TypeDescription string             `json:"type_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WorldTypeAttribute struct {
	TypeID      pgtype.UUID `json:"type_id"`
	AttributeID pgtype.UUID `json:"attribute_id"`
	Ordinal     int32       `json:"ordinal"`
	IsRequired  bool        `json:"is_required"`
}
