// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttributeDefinition(ctx context.Context, db DBTX, arg *CreateAttributeDefinitionParams) (*WorldAttributeDefinition, error)
	CreateEntity(ctx context.Context, db DBTX, arg *CreateEntityParams) (*WorldEntity, error)
	CreateEntityAssociation(ctx context.Context, db DBTX, arg *CreateEntityAssociationParams) (*WorldEntityAssociation, error)
	CreateEntityHistory(ctx context.Context, db DBTX, arg *CreateEntityHistoryParams) (*WorldEntityHistory, error)
	CreateType(ctx context.Context, db DBTX, arg *CreateTypeParams) (*WorldType, error)
	CreateTypeAttribute(ctx context.Context, db DBTX, arg *CreateTypeAttributeParams) (*WorldTypeAttribute, error)
	GetAttributeByWBATN(ctx context.Context, db DBTX, wbatn string) (*WorldAttributeDefinition, error)
	GetAttributesForType(ctx context.Context, db DBTX, typeID uuid.UUID) ([]*WorldAttributeDefinition, error)
	GetEntitiesByCriteria(ctx context.Context, db DBTX, arg *GetEntitiesByCriteriaParams) ([]*WorldEntity, error)
	GetEntitiesByParent(ctx context.Context, db DBTX, parentID uuid.UUID) ([]*WorldEntity, error)
	GetEntitiesByWBRN(ctx context.Context, db DBTX, wbrn string) ([]*WorldEntity, error)
	GetEntity(ctx context.Context, db DBTX, id uuid.UUID) (*WorldEntity, error)
	GetEntityAssociationsForEntity(ctx context.Context, db DBTX, entityOne uuid.UUID) ([]*WorldEntityAssociation, error)
	GetEntityAttributes(ctx context.Context, db DBTX, entityID uuid.UUID) ([]*WorldEntityAttribute, error)
	GetEntityByWBRN(ctx context.Context, db DBTX, wbrn string) (*WorldEntity, error)
	GetEntityChildReferences(ctx context.Context, db DBTX, parentID uuid.UUID) ([]*GetEntityChildReferencesRow, error)
	GetEntityHistory(ctx context.Context, db DBTX, entityID uuid.UUID) ([]*WorldEntityHistory, error)
	GetEntityReference(ctx context.Context, db DBTX, id uuid.UUID) (*GetEntityReferenceRow, error)
	GetEntityReferenceByWBRN(ctx context.Context, db DBTX, wbrn string) (*GetEntityReferenceByWBRNRow, error)
	GetFullTypeAttributes(ctx context.Context, db DBTX, typeID uuid.UUID) ([]*GetFullTypeAttributesRow, error)
	GetTypeByID(ctx context.Context, db DBTX, id uuid.UUID) (*WorldType, error)
	GetTypeByWBTN(ctx context.Context, db DBTX, wbtn string) (*WorldType, error)
}

var _ Querier = (*Queries)(nil)
